version: "3.9"

services:
  # postgres:
  #   image: postgres:15-alpine # ✅ Lighter base image
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: online-shopping
  #   ports:
  #     - "5428:5432"
  #   volumes:
  #     - db:/var/lib/postgresql/data
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 384M

  # dragonfly:
  #   image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.16.0
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   command: ["--cache_mode"]
  #   volumes:
  #     - dragonfly:/data
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 128M

  scylladb:
    image: scylladb/scylla:5.4
    restart: unless-stopped
    command: --smp 1 --memory 500M --overprovisioned 1
    ports:
      - "9042:9042"
      - "9160:9160"
    volumes:
      - scylla:/var/lib/scylla
    deploy:
      resources:
        limits:
          memory: 512M

  elasticsearch:
    image: elasticsearch:8.13.0
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms256m -Xmx256m # ✅ Reduced memory
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 384M

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    deploy:
      resources:
        limits:
          memory: 128M

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PARTITION_COUNT: 1
      KAFKA_REPLICATION_FACTOR: 1
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  # db:
  # dragonfly:
  scylla:
  esdata:
