version: "3.9"

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=online-shopping
    ports:
      - "5428:5432"
    volumes:
      - db:/var/lib/postgresql/data

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    restart: always
    ports:
      - "6379:6379"
    command: ["--cache_mode"]
    volumes:
      - dragonfly:/data

  scylladb:
    image: scylladb/scylla:latest
    restart: always
    command: --smp 1 --memory 750M --overprovisioned 1
    ports:
      - "9042:9042"
      - "9160:9160"
    volumes:
      - scylla:/var/lib/scylla

  elasticsearch:
    image: elasticsearch:8.13.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PARTITION_COUNT: 1
      KAFKA_REPLICATION_FACTOR: 1

volumes:
  db:
    driver: local
  dragonfly:
    driver: local
  scylla:
    driver: local
  esdata:
    driver: local
